/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tdfiuahvafpsvohzgqsu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZml1YWh2YWZwc3ZvaHpncXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwMzM0MjYsImV4cCI6MjA4MDYwOTQyNn0.O7FI-1pQ-UiW3LXYobcJ87-ZpgWnqKyVQ96EP6v4Jrs"